# Config explanation - https://github.com/Prunt/RestrictedCreative/wiki/Config-explanation
database:
  type: sqlite
  username: root
  password: ''
  host: localhost
  port: 3306
  database: rc_database
  table: rc_table

converter:
  cc: cc_
  sc: blocks

general:
  save-interval: 6000
  track: true
  worldedit:
    enabled: false
    extended: false
  separate-invs: true
  remove-invalid-items: false
  disabled-worlds:
  - 'survival'
  command:
    description: 'Allows player to switch between creative and default gamemodes.'
    aliases:
    - 'restrictedcreative'
    - 'creative'
    - 'gmc'
    - 'gm1'
    - 'gm'
  regions:
    owner-based:
      enabled: false
      allow-members: true 
    whitelist:
      enabled: false
      list:
      - 'building_competition'
  armor:
    enabled: true
    color: 16711680
  permissions:
    enabled: false
    vault: false
    list:
    - 'prefix.creative'
    - '-prefix.survival'
  disable:
    move:
      below-y: -1
      above-y: -1
    interact:
      inventories: true
      entities: true
      breeding: true
    item:
      drop: true
      pickup: true
      throw: true
    commands:
    - '(.*)(buy|sell)(.*)'
    - '(.*)(chest)(.*)'
    combat:
      pvp: true
      pve: true
    creation:
      wither: true
      snow-golem: true
      iron-golem: true
      
messages:
  prefix: '&2&lCreative > '
  no-permission: '&cYou don''t have enough permissions to do that!'
  no-console: '&cThis command can only be used in-game.'
  disabled: '&cYou can''t do that in creative mode.'
  disabled-interact: '&cYou can''t do that, because that was modified in creative mode.'
  reloaded: '&aConfig reloaded!'
  db-load: '&eLoading data from database...'
  db-save: '&eSaving data to database...'
  db-added: '&eAdded %blocks% new blocks to database.'
  db-removed: '&eDeleted %blocks% old blocks from database.'
  db-deleted: '&eDeleted database. Full restart is required for changes to take effect.'
  db-loaded: '&eLoaded %blocks% blocks from database!'
  db-done: '&aDone! Took %mills%ms'
  creative-on: '&aCreative mode enabled!'
  creative-off: '&aCreative mode disabled!'
  wrong-convert: '&cCorrect usage: /rc convert <cc|gmi|sql>'
  wrong-block: '&cCorrect usage: /rc block <add|remove|info|stats>'
  cancel: '&cCancelled!'
  block-add: '&aRight-click a block/entity you want to add to the database. Type "/rc block add" again to cancel.'
  block-added: '&aAdded %material% to the database!'
  block-remove: '&aRight-click a block/entity you want to remove from the database. Type "/rc block remove" again to cancel.'
  block-removed: '&aRemoved %material% from the database!'
  block-info: '&aRight-click a block/entity you want to know more about. Type "/rc block info" again to cancel.'
  block-info-true: '&aBlock/entity %material% is placed in creative mode!'
  block-info-false: '&aBlock/entity %material% is not placed in creative mode.'
  disabled-region: '&cYou can''t do that outside the allowed region.'
  block-stats: '&eTotal creative placed blocks and entities: %total%'
  disabled-creature: '&cYou can''t do that, because a part of the creature was placed in creative mode.'
  break-block: ''

blacklists:
  items:
    name:
    - 'Cash'
    lore:
    - '$'
  place:
  - 'BEDROCK'
  - 'ENDER_PORTAL_FRAME'
  - 'TNT'
  - 'SAPLING'
  interact:
    in-hand:
    - 'SPLASH_POTION'
    - 'LINGERING_POTION' 
    - 'MONSTER_EGG'
    - 'FLINT_AND_STEEL'
    - 'FIREBALL'
    - 'EXP_BOTTLE'
    - 'INK_SACK'
    - 'EYE_OF_ENDER'
    - 'EGG'
    - 'LAVA_BUCKET'
    on-ground:
    - 'JUKEBOX'
    - 'FLOWER_POT'
    - 'SIGN_POST'
    - 'WALL_SIGN'
  break:
  - 'BEDROCK'
  - 'ENDER_PORTAL_FRAME'
  
whitelist: []
